### PR TITLE
Fix asynchronous printing

### LINKED ISSUE #238: Printing from GPU kernels during saturation adjustment generates gibberish
When multiple GPU threads fail during saturation adjustment, they attempt to simultaneously print output, resulting in unusable gibberish. Unfortunately this has the effect of hindering rather than helping debugging. Here is an example of the top of such output in a 2 degree simulation with 31 vertical levels with ClimaAtmos:

```julia
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
, T_guess=nothing    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod, T_guess=nothing    Method=NewtonsMethod, T_guess=nothing    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethodmaxiter reached in saturation_adjustment:
, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, ρ=0.000042, ρ=0.000042, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000043, ρ=0.000042, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, tol=0.003000
, tol=0.003000
maxiter reached in saturation_adjustment:
, T_guess=nothing, maxiter=3, maxiter=3, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, T_guess=nothing, T_guess=nothing, maxiter=3, ρ=0.000042maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
, T_guess=nothing, T_guess=nothing, T_guess=nothing, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, T_guess=nothing-----------------------------------------
-----------------------------------------
, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, maxiter=3, tol=0.003000
, tol=0.003000
-----------------------------------------
-----------------------------------------
, T_guess=nothing, T_guess=nothingmaxiter reached in saturation_adjustment:
, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing-----------------------------------------
, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, T_guess=nothing, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000-----------------------------------------
-----------------------------------------
, tol=0.003000
, tol=0.003000
-----------------------------------------
-----------------------------------------
, T_guess=nothing, T_guess=nothing, T_guess=nothing-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
, maxiter=3, T_guess=nothing, T_guess=nothing, T_guess=nothing-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
, T_guess=nothingmaxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
-----------------------------------------
, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, T=nan, e_int=-343677.437500, e_int=-343637.437500, e_int=-343748.875000, tol=0.003000
-----------------------------------------
, T=nan, T=nan, T=nan, T=nanmaxiter reached in saturation_adjustment:
, maxiter=3, T_guess=nothing, T_guess=nothing, T=nan    Method=NewtonsMethod, e_int=-329253.468750    Method=NewtonsMethod, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, maxiter=3, maxiter=3, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, tol=0.003000
, T_guess=nothing, T_guess=nothing    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethodmaxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethod    Method=NewtonsMethodmaxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, q_tot=0.000000, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
, tol=0.003000
maxiter reached in saturation_adjustment:
    Method=NewtonsMethodmaxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
maxiter reached in saturation_adjustment:
    Method=NewtonsMethod-----------------------------------------
, T_guess=nothing-----------------------------------------
-----------------------------------------
, T_guess=nothing, maxiter=3-----------------------------------------
-----------------------------------------
-----------------------------------------
, maxiter=3, maxiter=3, maxiter=3-----------------------------------------
-----------------------------------------
-----------------------------------------
-----------------------------------------
```

### PR DESCRIPTION
**Pull request by charleskawczynski**
Closes #238.

### CODE REVIEW

File: src/relations.jl [hunk 1]
```diff
@@ -1744,16 +1743,15 @@ See also [`saturation_adjustment`](@ref).
...
-            KA.@print(", maxiter=", maxiter)
-            KA.@print(", tol=", tol.tol, "\n")
+            print_warning_peq(
+                sat_adjust_method,
+                p,
+                e_int,
+                q_tot,
+                sol.root,
+                maxiter,
+                tol.tol,
```
Comment (glwagner) [inline src/relations.jl:1753]: This pattern is repeated a few times:

```julia
print_warning(method, root, iter, tol, state)
```

If you abstract `state` with a type, you don't need many method.

Comment (glwagner) [reply src/relations.jl:1753]: Just an idea, I am not sure if this would work. A more generalizable strategy for handling adjustment failure might be to use something like

```julia
# default
adjustment_failure(args...) = print_warning(args...)

# inside the solver
!sol.converged && adjustment_failure(args...)
```

Then to turn this off users would write

```julia
using Thermodynamics
Thermodynamics.adjustment_failure(args...) = nothing
```

but users could also write other things, like custom messages or errors.

Comment (charleskawczynski) [reply src/relations.jl:1753]: `state`?

Comment (charleskawczynski) [reply src/relations.jl:1753]: Printing on the gpu is extremely limited, we can't even pass `", "` through to `print_warning_peq`, as this is not a literal.

Comment (glwagner) [reply src/relations.jl:1753]: how is that relevant ?

Comment (glwagner) [reply src/relations.jl:1753]: Sorry if I was unclear. My point was just to define something like

```julia
struct HPQVars
h; p; q
end

struct ρPQVars
ρ; p; q
end

then you only need one `print_warning`:

```julia
print_warning(solver_args, state::ρPQVars) = print_warning_ρpq(solver_args..., state...)
```

Having this in turn enables a more modular design for other things, such as generalizing the concept of "what to do when not converged".

Comment (charleskawczynski) [reply src/relations.jl:1753]: We could do that, I'm not sure it's worth the abstraction though

Comment (glwagner) [reply src/relations.jl:1753]: yeah, thats a different question. I have noticed quite a few functions that look like `_ρpq` though.

Comment (charleskawczynski) [reply src/relations.jl:1753]: I think the changes in this PR are an objective improvement. Alright if we merge this and iterate / see how this goes?

Comment (glwagner) [reply src/relations.jl:1753]: yes that fine.
